### ISSUE TITLE
ReportPortal Stucks Forever with Pytest -x or Pytest maxfail=1

### ISSUE THREAD

**Issue by anikettare** [reportportal/agent-python-pytest#151]
Hi I am Using Pytest with ReportPortal Whenever I used Pytest -x or Pytest maxfail=1 the Test-Suit Stuck at both on  cmd as well as on UI please Provide the solution.

**Comment by iivanou** [comment]
@anikettare Could you please confirm if changes from #152 resolve the issue? Thanks.

**Comment by anikettare** [comment]
Yes after making Changes in test_plugin.py mentioned in #152 it is working fine on cmd.
I tried with Two options maxfail=1 and   maxfail=2 and the execution was successful .
<img width="721" alt="Screenshot 2019-12-11 at 2 50 45 PM" src="https://user-images.githubusercontent.com/58687271/70608577-5cd4b400-1c26-11ea-9d42-6ff0a3265810.png">

But On UI i could see the the Test Suit is still in Running State.

 
<img width="1399" alt="Screenshot 2019-12-11 at 2 47 38 PM" src="https://user-images.githubusercontent.com/58687271/70608776-b806a680-1c26-11ea-9f24-7fea99f3f35d.png">

Test Command and Results on UI are attached in the form of Screenshot.

**Comment by iivanou** [comment]
@anikettare The test suite is shown as in progress because RP can't calculate execution time. All the tests are being correctly reported along with the test launch itself. From my point of view, the issue has been fixed. Reach out to @DzmitryHumianiuk in order to get details regarding the running state.

**Comment by DzmitryHumianiuk** [comment]
@iivanou @anikettare 
state on the screen above means that launch stays in progress.
If whole execution terminated by the reason of runner, it should finalize all related parents.
Suite and Launch itself.

In version 5 you can send only finishRQ for Launch, child suites will be stopped by server.

In general, if nothing says to RP that launch finished, RP knows nothing.
that's exactly what we see on the screen above

**Comment by anikettare** [comment]
@DzmitryHumianiuk So do i need to upgrade version to solve this Issue because the test remains in progress state on RP forever.

**Comment by DzmitryHumianiuk** [comment]
@anikettare nope, looks like you need one more upgrade in #152 

@iivanou in #152 you send only Suite finish RQ?
if you know that whole session can be terminated now, then just send `finishLaunchRQ` instead.

**Comment by iivanou** [comment]
@DzmitryHumianiuk I verified with Python debugger that the results of the test items and the launch itself are being sent out to RP(See line 107 of the plugin.py). What I can notice is that the test suite is stuck in the progress state as well. I suspect it may be a reason why RP is continuing to treat the launch as running too. I'm sure it's something that he can handle with the Pytest due to the nature of the usage. Will figure it out later.

**Comment by DzmitryHumianiuk** [comment]
@iivanou it's under v4 of RP?
In version RP4 you should finish test case, finish suite, finish launch respectively, keeping named sequence.
or Send `Force Finish` call.

In version RP5 it's enough to finish launch only.

**Comment by iivanou** [comment]
@anikettare I made more changes within #152. Could you please apply chose and provide your feedback? Thanks. We will release a new version of the agents if this PR is acceptable for you.

**Comment by iivanou** [comment]
@DzmitryHumianiuk Dzmitry, let's merge #152  and close the issue. I tested it on my own.

**Comment by DzmitryHumianiuk** [comment]
merged
